name: "main"

on:
  branches:
    - "main"
  workflow_dispatch:

jobs:
  spec:
    name: "Spec tests (Puppet: ${{matrix.puppet_version}}, Ruby Ver: ${{matrix.ruby_version}})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - puppet_version: "~> 7.24"
            ruby_version: "2.7"
          - puppet_version: "~> 8.0"
            ruby_version: "3.2"

    env:
      BUNDLE_WITHOUT: release_prep
      PUPPET_GEM_VERSION: ${{ matrix.puppet_version }}

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: ${{matrix.ruby_version}}
          bundler-cache: true

      - name: "Bundle environment"
        run: |
          echo ::group::bundler environment
          bundle env
          echo ::endgroup::

      - name: "Run Static & Syntax Tests"
        run: |
          bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
          bundle exec dependency-checker metadata.json

      - name: "Run tests"
        run: |
          bundle exec rake spec

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-puppet-${{matrix.puppet_version}}-ruby-${{matrix.ruby_version}}
          parallel: true

  finish:
    needs: spec
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
